export const timelineData = [
  {
    id: 's1',
    progress: 0.080,
    year: '2021',
    title: 'Founded in Hyderabad',
    description: 'A studio, a shed, and a conviction that precision could be manufactured.',
    url: 'https://www.oknomodhomes.com/',
    source: 'OKNO MODHOMES',
    image: '/assets/about/IMG_20260813_132709.jpg',
    className: 's1',
  },
  {
    id: 's2',
    progress: 0.215,
    year: '2022',
    title: 'The first home delivered',
    description: 'Drawn, panelised, and standing — the system proved on a single house.',
    url: 'https://www.oknomodhomes.com/models/forza',
    source: 'OKNO MODHOMES',
    image: '/assets/about/IMG_20260813_132728.jpg',
    className: 's2',
  },
  {
    id: 's3',
    progress: 0.350,
    year: '2023',
    title: 'The factory at Kothur',
    description: 'A real production line, and with it a real promise: ninety days, in writing.',
    url: 'https://www.oknomodhomes.com/models/orgo',
    source: 'OKNO MODHOMES',
    image: '/assets/about/IMG_20260813_132830.jpg',
    className: 's3',
  },
  {
    id: 's4',
    progress: 0.485,
    year: '2024',
    title: 'Mehul Valley — 17 units, Lonavala',
    description: 'Hospitality at scale, monsoon included, delivered on schedule.',
    url: 'https://www.oknomodhomes.com/models/tengo',
    source: 'OKNO MODHOMES',
    image: '/assets/about/IMG_20260813_133034.jpg',
    className: 's4',
  },
  {
    id: 's5',
    progress: 0.620,
    year: '2024',
    title: 'IGBC Green Gold',
    description: 'The system certified — audited, not asserted.',
    url: 'https://www.oknomodhomes.com/models/kray',
    source: 'OKNO MODHOMES',
    image: '/assets/about/award-feature.jpeg',
    className: 's5',
  },
  {
    id: 's6',
    progress: 0.755,
    year: '2025',
    title: 'Export 01 — India → United States',
    description: 'The country\'s first panelised home export. The road became an ocean.',
    url: 'https://www.oknomodhomes.com/gallery',
    source: 'OKNO MODHOMES',
    image: '/assets/about/award-certificate.jpeg',
    className: 's6',
  },
  {
    id: 's7',
    progress: 0.890,
    year: '2026',
    title: 'Sixty-five homes. Seventeen features.',
    description: 'AD India, Dezeen, Elle Decor among them — and a record that keeps growing.',
    url: 'https://www.oknomodhomes.com/collabs',
    source: 'OKNO MODHOMES',
    image: '/assets/about/Screenshot_2026-08-13-13-20-32-62_c37d74246d9c81aa0bb824b57eaf7062.jpg',
    className: 's7',
  }
];
